FROM redis:7

USER redis

# ENV REDIS_USER=${CACHE_REDIS_USER}
# ENV REDIS_PASSWORD=${CACHE_REDIS_PASSWORD}

# # in our entrypoint, we persist the auth configuration
# COPY entrypoint.sh /usr/local/bin
# RUN mkdir -p /data && chown -R redis:redis /data


# ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]

# TODO set config file with azure services
